# Generated by Django 6.0 on 2026-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service price at time of booking', max_digits=10),
        ),
    ]
