# Generated by Django 6.0 on 2026-03-24 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
