# Generated by Django 6.0 on 2026-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_type',
            field=models.CharField(choices=[('pay_later', 'Pay Later'), ('pay_now', 'Pay Now'), ('both', 'Both')], default='pay_later', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('range', 'Range')], default='fixed', max_length=20),
        ),
    ]
